#!/bin/bash
cluster_sim='/sci/labs/tsvi/nuria.nav/Simulations/'
local_sim='/Users/nunina/MESA/Simulations/'

if [ $# -eq 1 ]; then
    cd $local_sim && mkdir -p $1 && rsync -ave "ssh -p 12345" --include='history.data' --include='*/' --exclude='*' --prune-empty-dirs nuria.nav@localhost:$cluster_sim/$1/ $local_sim/$1
else
    echo "The right usage is ./script FOLDER_TO_COPY"
fi

