#!/bin/bash
local_sim='/Users/nunina/MESA/Simulations/MS'
folders="3M1Z 3M01Z 2M1Z 2M01Z 1.5M1Z 1.5M01Z 1M1Z 1M01Z 0.8M01Z"

for folder in $folders; do
    cd $local_sim/$folder && mkdir normal && rm -rf LOGS_1 && rm -rf LOGS_2 && mv LOGS_3 normal/RG && mv LOGS_4 normal/AGB && mv LOGS_5 normal/TPAGB && mkdir strip01 && mv LOGS_strip01* strip01 && mkdir strip02 && mv LOGS_strip02* strip02 && mkdir strip03 && mv LOGS_strip03* strip03 && mkdir strip04 && mv LOGS_strip04* strip04 && mkdir strip05 && mv LOGS_strip05* strip05  
done


